VERSION=1.0.0
VERTITLE=Cat

help:
	@echo "Makefile for MeteorOS version ${VERSION}, ${VERTITLE}"
	@echo ""
	@echo "Operands: [ all | help | clean ]"
	@echo ""

all:
	@echo "Making KERNEL"
	@echo "Making SDK"
	@echo "Making USERLAND"

clean:
	